# Farion config file
Bot:
    DCCPassword: changeme
    Nick: Chatbot
    NickServ: woowoo
    RetryConnect: true
Server:
    Hostname: irc.esper.net
    Port: 6697
    SSL: true
Channel:
    Name: "#channel"
ModChannel:
    Name: "#channel"
RemoteConsoleUsers:
    - "Username"