# Farion config file
Bot:
    DCCPassword: "changeme"
    Nick: "Chatbot"
    NickServ: "woowoo"
    RetryConnect: true
Server:
    Hostname: irc.esper.net
    Port: 6667
    SSL: false
    Password: ""
Channel:
    Name: "#channel"
    ShowJoins: true
    ShowParts: true
    ShowNickChanges: true
ModChannel:
    Name: "#channel"
RemoteConsoleUsers:
    - "Username"
Message:
    IrcMessage: "<{username}> {message}"
    IrcMeMessage: "* {username} {message}"
    GameMessage: "&r[IRC] <{nickname}> {message}"
    GameMeMessage: "&r[IRC] * {nickname} {message}"
    JoinMessage: ""
    PartMessage: ""
    NickMessage: ""
