# Farion config file
Bot:
    DCCPassword: "changeme"
    Nick: "Chatbot"
    NickServ: "woowoo"
    RetryConnect: true
Server:
    Hostname: irc.esper.net
    Port: 6667
    SSL: false
    Password: ""
Channel:
    Name: "#channel"
ModChannel:
    Name: "#channel"
RemoteConsoleUsers:
    - "Username"
Message:
    # Game -> IRC
    Irc:
        Message: "<{username}> {message}"
        MeMessage: "* {username} {message}"
    # IRC -> Game
    Game:
        Message: "&r[IRC] <{nickname}> {message}"
        MeMessage: "&r[IRC] * {nickname} {message}"
        JoinMessage: "&r[IRC] {nickname} has joined."
        PartMessage: "&r[IRC] {nickname} has left."
        NickMessage: "&r[IRC] {oldnick} is now {newnick}"
